# Generated by Django 4.0.5 on 2022-06-04 13:31

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pastes", "0006_paste_exposure"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="paste",
            managers=[
                ("published", django.db.models.manager.Manager()),
            ],
        ),
    ]
