# Generated by Django 4.0.5 on 2022-07-04 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0024_alter_paste_syntax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paste',
            old_name='expiration_interval_symbol',
            new_name='expiration_symbol',
        ),
    ]
