# Generated by Django 4.0.5 on 2022-07-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0025_rename_expiration_interval_symbol_paste_expiration_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
