# Generated by Django 5.1.6 on 2025-02-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0026_alter_paste_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='title',
            field=models.CharField(blank=True, default='Untitled', max_length=50),
        ),
    ]
