# Generated by Django 4.0.5 on 2022-07-04 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_preferences_default_syntax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferences',
            old_name='default_expiration_interval_symbol',
            new_name='default_expiration_symbol',
        ),
    ]
