# Generated by Django 4.0.6 on 2022-08-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='layout_width',
            field=models.CharField(choices=[('N', 'Fixed (narrow)'), ('W', 'Fluid (wide)')], default='N', max_length=1, verbose_name='Layout Width'),
        ),
    ]
