# Generated by Django 4.0.6 on 2022-08-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_preferences_layout_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='paste_font_size',
            field=models.CharField(choices=[('11', 'Small'), ('12', 'Normal'), ('13', 'Bigger'), ('14', 'Huge')], default='12', max_length=2, verbose_name='Paste Font Size'),
        ),
    ]
