# Generated by Django 4.0.6 on 2022-08-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_preferences_paste_font_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='paste_font_size',
            field=models.CharField(choices=[('11', 'Small'), ('13', 'Normal'), ('14', 'Bigger'), ('15', 'Huge')], default='13', max_length=2, verbose_name='Paste Font Size'),
        ),
    ]
