# Generated by Django 4.0.5 on 2022-06-03 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('syntax', models.CharField(max_length=50)),
                ('expiration_time', models.TimeField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('burn_after_read', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
