# Generated by Django 4.0.5 on 2022-06-03 09:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0002_paste_uuid_alter_paste_syntax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
