# Generated by Django 4.0.5 on 2022-06-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pastes", "0003_alter_paste_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="paste",
            name="content_html",
            field=models.TextField(blank=True),
        ),
    ]
