# Generated by Django 4.0.5 on 2022-06-04 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0007_alter_paste_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='paste',
            managers=[
            ],
        ),
    ]
