# Generated by Django 4.0.5 on 2022-06-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0013_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
