# Generated by Django 4.0.5 on 2022-06-17 08:41

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pastes", "0019_paste_filesize_alter_paste_syntax"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paste",
            name="expiration_time",
            field=models.DurationField(
                blank=True,
                choices=[
                    ("", "Never"),
                    (datetime.timedelta(seconds=600), "10 minutes"),
                    (datetime.timedelta(seconds=3600), "1 Hour"),
                    (datetime.timedelta(days=1), "1 Day"),
                    (datetime.timedelta(days=7), "1 Week"),
                    (datetime.timedelta(days=14), "2 Weeks"),
                    (datetime.timedelta(days=30), "1 Month"),
                    (datetime.timedelta(days=180), "6 Month"),
                    (datetime.timedelta(days=365), "1 Year"),
                ],
                null=True,
            ),
        ),
    ]
